[package]
name = "readmem"
description = "Read support for Verilog $readmemb/$readmemh files"
version = "0.1.0"
authors = ["jade <software@lfcode.ca>"]
edition = "2018"

[dev-dependencies]
doc-comment = "0.3.3"

[dependencies]
pest = "2.1.3"
pest_derive = "2.1.0"
thiserror = "1.0.21"
